AWSTemplateFormatVersion: 2010-09-09
Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            -
                Label:
                    default: 'S3 Artifacts'
                Parameters:
                    - s3Name
            -
                Label:
                    default: 'Role codepipeline'
                Parameters:
                    - Rname

        ParameterLabels:
            s3Name:
                default: 'Ingrese el nombre del bucket'
            Rname:
                default: 'Ingrese el nombre del role de IAM'

Parameters:
    s3Name:
        Description: Nombre
        Type: String
    Rname:
        Description: Llave
        Type: String
     
Resources:
    s3:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL: https://demopipelinesimon.s3.us-east-1.amazonaws.com/s3.yaml
            Parameters:
                s3Name: !Ref s3Name
    iam:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL: https://demopipelinesimon.s3.us-east-1.amazonaws.com/iam.yaml
            Parameters:
                s3ARN: !GetAtt s3.Outputs.s3artifactsArn    
                Rname: !Ref Rname