AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    s3Name:
        Type: String

Resources:
  rs3:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      BucketName: !Ref s3Name
Outputs:
  s3name:
      Value: !Ref rs3
      Export:
        Name: s3artifacts
  s3arn:
      Value: !GetAtt rs3.Arn
      Export:
        Name: s3artifactsArn